import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F5F5' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 15, paddingBottom: 20 },
  backButton: { padding: 5 },
  headerTitle: { fontSize: 22, fontWeight: '700', color: '#0F172A' },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },
  
  // SECCIÓN 1: FORMULARIO
  machineInfoContainer: { marginBottom: 15 },
  machineTitleRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  machineName: { fontSize: 22, fontWeight: '700', color: '#0F172A', marginLeft: 10, flex: 1 },
  badgePreventivo: { flexDirection: 'row', backgroundColor: '#F59E0B', alignSelf: 'flex-end', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, alignItems: 'center', marginTop: -20 },
  badgeIcon: { marginRight: 5 },
  badgeText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
  instructions: { fontSize: 16, fontWeight: '500', color: '#0F172A', lineHeight: 22, marginBottom: 20 },
  photoContainer: { backgroundColor: '#E2E8F0', height: 180, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginBottom: 20, position: 'relative' },
  newPhotoButton: { position: 'absolute', bottom: -15, right: 20, backgroundColor: '#2F9E44', flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 15, borderRadius: 8, elevation: 4 },
  newPhotoText: { color: '#FFFFFF', fontWeight: '700', fontSize: 16, marginLeft: 8 },
  audioContainer: { backgroundColor: 'rgba(11, 58, 110, 0.05)', borderWidth: 1, borderColor: 'rgba(11, 58, 110, 0.2)', borderRadius: 10, padding: 15, marginBottom: 25, marginTop: 10 },
  audioHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  audioTitle: { fontSize: 16, fontWeight: '600', color: '#000000', marginLeft: 10 },
  textLight: { fontWeight: '400', color: '#717171' },
  audioPlayer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 10, padding: 10 },
  audioTime: { fontSize: 16, fontWeight: '600', color: '#0F172A', marginLeft: 10 },
  progressBar: { flex: 1, height: 4, backgroundColor: '#E2E8F0', marginHorizontal: 10, borderRadius: 2 },
  progressFill: { width: '30%', height: '100%', backgroundColor: '#0F172A', borderRadius: 2 },
  sendIcon: { marginLeft: 15 },
  inputLabel: { fontSize: 18, fontWeight: '700', color: '#0F172A', marginBottom: 10 },
  inputContainer: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, height: 120, padding: 15, marginBottom: 15 },
  textInput: { flex: 1, fontSize: 16, color: '#0F172A' },
  charCount: { textAlign: 'right', fontSize: 12, color: '#717171', marginTop: 5 },
  noteContainer: { flexDirection: 'row', backgroundColor: 'rgba(11, 58, 110, 0.05)', padding: 15, borderRadius: 10, alignItems: 'center' },
  noteText: { flex: 1, fontSize: 13, color: '#0F172A', marginLeft: 10, lineHeight: 18 },
  divider: { height: 1, backgroundColor: '#D9D9D9', marginVertical: 30 },

  // SECCIÓN 2: FEED
  sectionTitle: { fontSize: 20, fontWeight: '700', color: '#000000', marginBottom: 15 },
  reportItem: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 15, marginBottom: 15, borderWidth: 1, borderColor: '#E2E8F0' },
  reportHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  reportStatus: { flexDirection: 'row', alignItems: 'center' },
  statusText: { fontSize: 16, fontWeight: '700', color: '#0F172A', marginLeft: 5 },
  reportDate: { fontSize: 13, color: '#717171' },
  reportDesc: { fontSize: 16, color: '#0F172A', marginBottom: 10 },
  linkButton: { flexDirection: 'row', alignItems: 'center', marginTop: 5 },
  linkText: { fontSize: 14, color: '#0B3A6E', marginRight: 5 },
  newReportButton: { flexDirection: 'row', backgroundColor: '#FFFFFF', padding: 15, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 20 },
  newReportText: { fontSize: 16, fontWeight: '700', color: '#0F172A', marginLeft: 10 },
  emergencyBanner: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0' },
  emergencyLeft: { backgroundColor: '#DC2626', padding: 15, justifyContent: 'center', alignItems: 'center', width: '40%' },
  emergencyTitle: { color: '#FFFFFF', fontWeight: '700', marginBottom: 5 },
  emergencyRight: { flexDirection: 'row', padding: 15, alignItems: 'center', width: '60%' },
  emergencyNumber: { fontSize: 24, fontWeight: '900', color: '#000000', marginLeft: 10 },
  emergencySub: { fontSize: 12, color: '#717171', marginLeft: 10 },

  // SECCIÓN 3: DASHBOARD
  qrBigButton: { flexDirection: 'row', backgroundColor: '#4C84E6', borderRadius: 10, padding: 18, alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  qrBigText: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  metricsCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 15, marginBottom: 20, elevation: 2 },
  metricsTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  metricItem: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  metricDivider: { width: 1, height: 40, backgroundColor: '#E2E8F0', marginHorizontal: 15 },
  metricValueGreen: { fontSize: 22, fontWeight: '700', color: '#2F9E44', marginLeft: 10 },
  metricValueBlack: { fontSize: 22, fontWeight: '700', color: '#0F172A', marginLeft: 10 },
  metricLabel: { fontSize: 12, color: '#0F172A', marginLeft: 10 },
  metricsBottom: { flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#E2E8F0', paddingTop: 15 },
  metricHighlight: { fontSize: 16, fontWeight: '700', color: '#0F172A', marginLeft: 10 },
  actionMenuCard: { backgroundColor: '#FFFFFF', borderRadius: 10, marginBottom: 20, elevation: 2 },
  menuRow: { flexDirection: 'row', alignItems: 'center', padding: 15 },
  menuText: { flex: 1, fontSize: 16, fontWeight: '600', color: '#0F172A', marginLeft: 15 },
  menuLine: { height: 1, backgroundColor: '#E2E8F0' },
  helpText: { fontSize: 14, color: '#717171', textAlign: 'center', marginBottom: 20, paddingHorizontal: 10 },
  templateCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 15, elevation: 2 },
  templateHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F5F5F5', padding: 10, borderRadius: 8, marginBottom: 15 },
  templateTitle: { fontSize: 16, fontWeight: '700', color: '#0F172A', marginLeft: 10 },
  templateLine: { height: 1, backgroundColor: '#E2E8F0', marginBottom: 15 },

  // BOTTOM NAV
  bottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', backgroundColor: '#FFFFFF', paddingVertical: 10, justifyContent: 'space-around', borderTopLeftRadius: 20, borderTopRightRadius: 20, elevation: 10 },
  navItem: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  navText: { fontSize: 12, fontWeight: '500', color: '#0F172A', marginTop: 4 }
});