import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F5F5' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 15, paddingBottom: 15 },
  backButton: { padding: 5 },
  headerTitle: { fontSize: 28, fontWeight: '700', color: '#0F172A', marginLeft: 15 },
  headerIconContainer: { flexDirection: 'row', position: 'relative', paddingRight: 10 },
  chatBubbleIcon: { position: 'absolute', top: -5, right: -5, backgroundColor: '#F5F5F5', borderRadius: 10, padding: 2 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },
  subheader: { fontSize: 16, fontWeight: '500', color: '#0F172A', textAlign: 'center', marginBottom: 25 },
  separator: { color: '#717171', fontWeight: '300' },
  contactCard: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 10, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: '#E2E8F0', elevation: 2 },
  cardIcon: { marginRight: 20, marginTop: 5 },
  cardContent: { flex: 1 },
  cardTitle: { fontSize: 18, fontWeight: '700', color: '#000000', marginBottom: 5 },
  highlightBadge: { backgroundColor: 'rgba(245, 158, 11, 0.2)', alignSelf: 'flex-start', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 8, marginBottom: 5 },
  highlightText: { fontSize: 16, fontWeight: '700', color: '#000000' },
  cardSubtext: { fontSize: 13, color: '#717171' },
  faqHeader: { flexDirection: 'row', alignItems: 'center', marginTop: 15, marginBottom: 15, paddingHorizontal: 5 },
  faqTitle: { fontSize: 20, fontWeight: '700', color: '#0F172A', marginLeft: 10 },
  faqCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 20, borderWidth: 1, borderColor: '#E2E8F0', elevation: 2 },
  faqItem: { flexDirection: 'row', marginBottom: 20 },
  faqCheck: { marginRight: 10, marginTop: 2 },
  faqTextContainer: { flex: 1 },
  question: { fontSize: 14, fontWeight: '700', color: '#0B3A6E', marginBottom: 5 },
  answer: { fontSize: 13, color: '#000000', lineHeight: 18 },
  faqDivider: { height: 1, backgroundColor: '#E2E8F0', marginBottom: 15 },
  moreFaqButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  moreFaqText: { fontSize: 14, fontWeight: '600', color: '#0F172A' },
  bottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', backgroundColor: '#FFFFFF', paddingVertical: 10, justifyContent: 'space-around', borderTopLeftRadius: 20, borderTopRightRadius: 20, elevation: 10 },
  navItem: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  navItemActive: { position: 'relative' },
  navText: { fontSize: 12, fontWeight: '500', color: '#0F172A', marginTop: 4 },
  activeIndicator: { position: 'absolute', bottom: -10, width: '100%', height: 4, backgroundColor: '#717171', borderRadius: 2 }
});