spring.application.name=mantech

# ========================
# Base de datos PostgreSQL
# En Docker: sobreescrito por variables de entorno del docker-compose
# En local:  usa localhost:5432
# ========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mantech_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# Flyway
# ========================
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.encoding=UTF-8
spring.flyway.baseline-on-migrate=true

# ========================
# JWT
# ========================
jwt.secret=${JWT_SECRET:4d4a6f436e4c72576e5a7142764d466f4e6b6a304b65336b6f464a5259754d74}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ========================
# Server
# ========================
server.port=8080
