import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F5F5' },
  topHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 15, paddingBottom: 10, backgroundColor: '#F5F5F5' },
  logoContainer: { flexDirection: 'row', alignItems: 'baseline' },
  logoM: { fontSize: 32, fontWeight: '900', color: '#0B3A6E', marginRight: 8, fontStyle: 'italic' },
  logoTextBold: { fontSize: 22, fontWeight: '900', color: '#0F172A' },
  logoTextLight: { fontSize: 22, fontWeight: '400', color: '#0B3A6E' },
  headerIcons: { flexDirection: 'row' },
  iconSpacing: { marginHorizontal: 15 },
  headerDivider: { height: 1, backgroundColor: '#D9D9D9', marginHorizontal: 20, marginBottom: 15 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },
  machineHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  title: { fontSize: 24, fontWeight: '500', color: '#0F172A', marginRight: 15 },
  badge: { backgroundColor: '#2F9E44', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 5 },
  badgeText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
  qrCard: { backgroundColor: '#FFFFFF', borderRadius: 10, alignItems: 'center', marginBottom: 20, paddingTop: 40, paddingBottom: 20, paddingHorizontal: 20, elevation: 4, shadowColor: '#0F172A', shadowOpacity: 0.1, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
  qrIcon: { marginBottom: 30 },
  qrButton: { backgroundColor: '#4C84E6', width: '100%', paddingVertical: 15, borderRadius: 8, alignItems: 'center' },
  qrButtonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 18 },
  statusBarCard: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 10, paddingVertical: 12, paddingHorizontal: 15, justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, elevation: 3, shadowColor: '#0F172A', shadowOpacity: 0.1, shadowRadius: 3, shadowOffset: { width: 0, height: 2 } },
  statusItem: { flexDirection: 'row', alignItems: 'center' },
  statusText: { marginLeft: 5, fontSize: 16, fontWeight: '500', color: '#0F172A' },
  statusNumberText: { marginLeft: 5, fontSize: 18, fontWeight: '800', color: '#0F172A' },
  actionsCard: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 10, marginBottom: 20, elevation: 3, shadowColor: '#0F172A', shadowOpacity: 0.1, shadowRadius: 3, shadowOffset: { width: 0, height: 2 } },
  actionButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 20 },
  actionText: { fontWeight: '700', fontSize: 16, color: 'rgba(15, 23, 42, 0.8)', marginLeft: 10 },
  verticalDivider: { width: 1, backgroundColor: '#E2E8F0', marginVertical: 15 },
  infoCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 20, marginBottom: 25, elevation: 3, shadowColor: '#0F172A', shadowOpacity: 0.1, shadowRadius: 3, shadowOffset: { width: 0, height: 2 } },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  infoText: { fontSize: 14, fontWeight: '500', color: '#0F172A', marginLeft: 15, flex: 1 },
  aboutUsContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 40, paddingLeft: 10 },
  aboutUsText: { fontSize: 20, fontWeight: '700', color: '#000000', marginLeft: 10 },
  bottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', backgroundColor: '#FFFFFF', paddingVertical: 10, justifyContent: 'space-around', borderTopLeftRadius: 20, borderTopRightRadius: 20, elevation: 10, shadowColor: '#0F172A', shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: -5 } },
  navItem: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  navItemActive: { position: 'relative' },
  navText: { fontSize: 12, fontWeight: '500', color: '#0F172A', marginTop: 4 },
  activeIndicator: { position: 'absolute', bottom: -10, width: '100%', height: 4, backgroundColor: '#717171', borderRadius: 2 }
});